version: '3.1'

services:

  app:
    restart: always
    depends_on:
      - mongo
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3001:3001"
    working_dir: /app/api
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "3001"
      ]
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    volumes:
      - /var/data/mongo:/data/db
